import type { AdminPackage, CreatorPricing } from "@/lib/admin/package-types";

export const defaultCreatorPricing: CreatorPricing = {
  regularPrice: 79,
  offerPrice: 19,
  offerStarts: "2026-06-24T07:53:00.000Z",
  offerEnds: "2026-07-24T07:53:00.000Z",
  currency: "usd",
  ctaLabel: "Start building",
  available: true,
  features: [
    "One SEO-ready creator profile",
    "Unlimited VidCarry secure cloud hosting and unlimited hosted projects",
    "Unlimited YouTube, Vimeo, and external embeds",
    "Three premium portfolio themes",
    "Analytics and inquiry inbox",
    "Public creator directory eligibility",
    "All current and future VidCarry resources",
  ],
};

export const defaultAdminPackages: AdminPackage[] = [
  {
    id: "161c0279-25dc-4067-9ca8-351ac1d86264",
    slug: "ugc-ad-sprint",
    title: "UGC Ad Sprint",
    eyebrow: "Fast creative testing",
    thumbnailLabel: "UGC",
    thumbnailGradient: "linear-gradient(145deg,#08192b,#007bbd 52%,#00a8ff)",
    bestFor: "Brands that need fresh hooks and creator-style ads fast.",
    timelineLabel: "7-14 business days after kickoff",
    status: "published",
    sortOrder: 10,
    summary:
      "A focused sprint that turns product angles, creator footage, and social proof into paid-social-ready UGC ad variants.",
    deliverables: [
      "Creative angle map",
      "Creator or model brief",
      "4-8 edited ad variants",
      "Platform-ready exports",
    ],
    includedItems: [
      "Research and angle planning",
      "Hook and script direction",
      "Editing, captions, sound, and exports",
      "One organized delivery hub",
    ],
    benefits: [
      "Launch more creative tests without coordinating multiple vendors",
      "Turn one footage set into multiple useful ad angles",
      "Keep strategy, production, and editing aligned",
    ],
    processSteps: [
      "Complete checkout and short brief",
      "Share footage or request production support",
      "VidCarry confirms kickoff and delivery date",
      "Review, revise, and download final assets",
    ],
    thumbnail: "/assets/thumbnails/packages/ugc-ad-sprint.svg",
    variants: [
      {
        id: "4199ba6c-1d98-407e-9721-c4accab9db2b",
        name: "Standard",
        billingType: "one_time",
        regularPrice: 1500,
        offerPrice: 550,
        offerStarts: null,
        offerEnds: null,
        currency: "usd",
        deliveryDays: 10,
        revisionRounds: 2,
        active: true,
        description: "Core sprint package",
        sortOrder: 10,
      },
    ],
    addOns: [],
  },
  {
    id: "2682fb70-55c6-49bc-94d6-6d6191a1dc65",
    slug: "editing-sprint",
    title: "Editing Sprint",
    eyebrow: "Production support",
    thumbnailLabel: "EDIT",
    thumbnailGradient: "linear-gradient(145deg,#101827,#0c4a6e 48%,#38bdf8)",
    bestFor: "Teams with footage that need a reliable editing engine.",
    timelineLabel: "5-10 business days after kickoff",
    status: "published",
    sortOrder: 20,
    summary:
      "A structured editing sprint for turning raw footage into polished, retention-focused social assets with clear feedback rounds.",
    deliverables: [
      "Footage review",
      "6-12 edited assets",
      "Captions and sound design",
      "Multiple platform exports",
    ],
    includedItems: [
      "Editorial direction and footage selects",
      "Pacing, captions, sound design, and polish",
      "Requested aspect-ratio exports",
      "Organized review and delivery",
    ],
    benefits: [
      "Clear a footage backlog quickly",
      "Create consistent quality across a campaign",
      "Use a predictable revision process",
    ],
    processSteps: [
      "Upload footage and references",
      "VidCarry confirms edit map",
      "First cuts move into client review",
      "Revisions are completed and finals delivered",
    ],
    thumbnail: "/assets/thumbnails/packages/editing-sprint.svg",
    variants: [
      {
        id: "551e4d34-a24c-4f3a-9e38-6c24b33ad3dd",
        name: "Standard",
        billingType: "one_time",
        regularPrice: 900,
        offerPrice: 170,
        offerStarts: null,
        offerEnds: null,
        currency: "usd",
        deliveryDays: 2,
        revisionRounds: 2,
        active: true,
        description: "Core editing package",
        sortOrder: 10,
      },
    ],
    addOns: [],
  },
  {
    id: "830f9828-253e-4187-b80b-b104e3518979",
    slug: "shoot-to-sales-sprint",
    title: "Shoot-to-Sales Sprint",
    eyebrow: "Full production",
    thumbnailLabel: "S2S",
    thumbnailGradient: "linear-gradient(145deg,#061822,#006678 48%,#00d4ff)",
    bestFor:
      "Brands that want strategy, talent, shooting, editing, and launch-ready ads.",
    timelineLabel: "15-25 business days after kickoff",
    status: "published",
    sortOrder: 30,
    summary:
      "An end-to-end production sprint covering creative strategy, creator or model production, editing, and launch-ready performance assets.",
    deliverables: [
      "Creative strategy workshop",
      "Talent sourcing and production brief",
      "Managed product shoot",
      "8-16 launch-ready ad assets",
    ],
    includedItems: [
      "Audience and offer research",
      "Concepts, scripts, casting, and shoot plan",
      "Production coordination",
      "Editing, variations, and delivery",
    ],
    benefits: [
      "Move from product to campaign with one accountable team",
      "Capture footage designed for testing, not only aesthetics",
      "Build a reusable creative library from one sprint",
    ],
    processSteps: [
      "Align on goals, product, and offer",
      "Approve concepts and talent direction",
      "Complete production and first edits",
      "Review, revise, and prepare launch assets",
    ],
    thumbnail: "/assets/thumbnails/packages/shoot-to-sales-sprint.svg",
    variants: [
      {
        id: "b489203a-92c5-41a2-b19f-31e30edb74ae",
        name: "Standard",
        billingType: "one_time",
        regularPrice: 3500,
        offerPrice: 950,
        offerStarts: null,
        offerEnds: null,
        currency: "usd",
        deliveryDays: 20,
        revisionRounds: 2,
        active: true,
        description: "Full production package",
        sortOrder: 10,
      },
    ],
    addOns: [],
  },
  {
    id: "8626e2f1-be8b-4417-a0f0-f6ed5a309626",
    slug: "paid-ads-sprint",
    title: "Paid Ads Sprint",
    eyebrow: "Ongoing growth",
    thumbnailLabel: "ADS",
    thumbnailGradient: "linear-gradient(145deg,#071827,#075985 48%,#0ea5e9)",
    bestFor:
      "Brands that need a recurring creative testing and paid-social support rhythm.",
    timelineLabel: "Monthly cycle; first plan within 5 business days",
    status: "published",
    sortOrder: 40,
    summary:
      "A monthly creative and media support system for structured testing, performance learning, and faster iteration.",
    deliverables: [
      "Monthly creative testing plan",
      "Fresh ad variants and cutdowns",
      "Performance review",
      "Iteration recommendations",
    ],
    includedItems: [
      "Monthly creative priorities",
      "Creative production and editing allocation",
      "Paid-social launch support",
      "Performance summary and next tests",
    ],
    benefits: [
      "Connect creative output to campaign learning",
      "Maintain a dependable monthly testing cadence",
      "Reduce time lost between insight and iteration",
    ],
    processSteps: [
      "Confirm monthly priorities",
      "Prepare and launch creative tests",
      "Review performance signals",
      "Build the next iteration cycle",
    ],
    thumbnail: "/assets/thumbnails/packages/paid-ads-sprint.svg",
    variants: [
      {
        id: "5230bf75-b977-4fbf-9cba-3b0ab6b7928a",
        name: "Monthly",
        billingType: "monthly",
        regularPrice: 2000,
        offerPrice: 700,
        offerStarts: null,
        offerEnds: null,
        currency: "usd",
        deliveryDays: 10,
        revisionRounds: 2,
        active: true,
        description: "Recurring creative and paid-social support",
        sortOrder: 10,
      },
    ],
    addOns: [],
  },
];
