import type { AdminTeamMember } from "@/lib/admin/team-types";

export const defaultAdminTeamMembers: AdminTeamMember[] = [
  {
    id: "seed-team-sahadat",
    slug: "md-sahadat-hosen",
    name: "Md. Sahadat Hosen",
    role: "Performance Ads & Growth Lead",
    initials: "SA",
    bio: "Leads conversion-focused ad direction, campaign testing, and sales-driven creative strategy for DTC and ecommerce brands.",
    image: "/assets/team/sahadat.jpg",
    linkedin: "https://www.linkedin.com/in/itsahadat/",
    profileHref: "",
    portfolioHref: "/portfolio/md-sahadat-hosen",
    status: "published",
    sortOrder: 10,
  },
  {
    id: "seed-team-neaz",
    slug: "neaz-mahmud",
    name: "Neaz Mahmud",
    role: "Founder & CEO",
    initials: "NM",
    bio: "Leads VidCarry's creative direction, production standards, UGC ad systems, and premium video editing workflow.",
    image: "/assets/team/neaz.jpg",
    linkedin: "https://www.linkedin.com/in/neazmahmud/",
    profileHref: "/team/neaz-mahmud",
    portfolioHref: "/portfolio/neaz-mahmud",
    status: "published",
    sortOrder: 0,
  },
  {
    id: "seed-team-sobuj",
    slug: "md-nur-alam",
    name: "Md Nur Alam",
    role: "Video Editor",
    initials: "NS",
    bio: "Creates clean performance edits, product demo cuts, UGC-style sequences, and fast social media campaign variations.",
    image: null,
    linkedin: "",
    profileHref: "",
    portfolioHref: "/portfolio/md-nur-alam",
    status: "published",
    sortOrder: 60,
  },
  {
    id: "seed-team-kawsar",
    slug: "kawsar-hossain",
    name: "Kawsar Hossain",
    role: "Video Editor",
    initials: "KH",
    bio: "Focuses on retention-minded cuts, visual polish, short-form structure, and ad-ready editing support for client campaigns.",
    image: null,
    linkedin: "",
    profileHref: "",
    portfolioHref: "/portfolio/kawsar-hossain",
    status: "published",
    sortOrder: 70,
  },
];
